# To enable pre-commit hooks, run:
#   pip install pre-commit
#   pre-commit install
# Or, if using Poetry:
#   poetry add --dev pre-commit
#   poetry run pre-commit install
# This will automatically format your code with black before each commit.

repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: [] 